In constraint validation errors, change how the parameter list is formatted
Instead of printing a comma-separated list of single labels:
- print a line for each parameter
- print both the short and long name of options.

# Example
Error: at least 1 of the following parameters must be set:
  ARG
  -o
  --one
  --two (-t)